title: <p align="center">Samuel<br>Deery-Schmitt</p>
logo: "/images/photo.png?raw=true" # your photo (or logo) here
description:
  <p align="center">
  <a href="pdf/Deery-Schmitt_Samuel_Resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/samds/">LinkedIn</a> |
  <a href="https://github.com/sampds">GitHub</a>
  </p>
  
  <p align="justify">
  Data Scientist
  <br><br>
  Recently finished a contract doing data modeling for a civil engineering firm that contracts with the United States Department of Defense.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-ZJR2M3XX12 # your Google Analytics tracking ID here
